# Numpy

- Numpy is a library for numerical operations in python.
- We can handle large, multi-dimensional arrays and matrices, along with a collection of high-level mathematical functions to operate on these arrays.

# NumPy Installation

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np #type:ignore
print(np.__version__)

2.0.0


# Numpy arrays

- Numpy arrays are similar data structures like python lists, but more efficient and optimized for numerical operations.

**Shape** function used to return a tuple representing the dimensions of the array.

In [4]:
a = np.array(["a","b","c"])
print(a.shape)

(3,)


In [5]:
b = np.array([[1,2,3],[4,5,6]])
print(b.shape)

(2, 3)


In [6]:
c= np.array([[[1]]])
print(c.shape)

(1, 1, 1)


**size** used to return the total number of elements in the array.

In [7]:
a = np.array([1,2,3,4,5,6,7,8,9,0])
print(a.size)

10


**dtype** represents the data type of the array elements.

In [8]:
a = np.array([1,2,3,4,5])
print(a.dtype)

int64


In [9]:
b = np.array([1.0,2.0])
print(b.dtype)

float64


In [11]:
c = np.array([56+64j])
print(c.dtype)

complex128


In [13]:
d = np.array([True, False])
print(d.dtype)

bool


Specify the data type when creating an array using the dtype parameter:

In [14]:
a = np.array([1,2,3],dtype=np.float32)
print(a)
print(a.dtype)

[1. 2. 3.]
float32


In [15]:
b = np.array([1, 2, 3], dtype=np.int16)
print(b)        
print(b.dtype) 

[1 2 3]
int16


# Commonly used functions

In [16]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [17]:
# np.asarray(): convert the input to an array
t = [1,2,3,4,5,6]
a = np.asarray(t)
print(a)

[1 2 3 4 5 6]


In [18]:
# from a tuple
f = (1,2,3)
a = np.asarray(f)
print(a)

[1 2 3]


In [19]:
# np.ones(): create an array filled with ones
a = np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [20]:
# can also create a 2D array of ones with shape (3,4)
b = np.ones((3,4))
print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [21]:
# np.zores: create a 1D array of zeros
a = np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [22]:
#can also create a 2D array of zeros with shape (5, 3)
a = np.zeros((5,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [24]:
# np.empty(): create an uninitialized array
a = np.empty(5)
print(a)

[0. 0. 0. 0. 0.]


In [26]:
# can also create a 2D array using np.empty() with shape (2, 3)
b = np.empty((2, 3))
print(b)

[[4.9e-324 9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323]]


In [27]:
# np.arange(): create a sequence of numbers within a range.
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [30]:
a = np.arange(2,6)
print(a)

[2 3 4 5]


In [34]:
a = np.arange(2,10,3)
print(a)

[2 5 8]


In [36]:
# np.linespace(): create an array with evenly spaced values within a range.
a = np.linspace(0, 5, 6)
print(a)

[0. 1. 2. 3. 4. 5.]


In [37]:
a = np.linspace(4,20,25)
print(a)

[ 4.          4.66666667  5.33333333  6.          6.66666667  7.33333333
  8.          8.66666667  9.33333333 10.         10.66666667 11.33333333
 12.         12.66666667 13.33333333 14.         14.66666667 15.33333333
 16.         16.66666667 17.33333333 18.         18.66666667 19.33333333
 20.        ]


In [38]:
# np.eye(): create a square identity matrix.
a = np.eye(2)
print(a)

[[1. 0.]
 [0. 1.]]


In [39]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [40]:
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# NumPy array operations and Broadcasting

**Basic Array Operations**

In [42]:
# Addition: Adds two arrays element-wise
a = np.array([1,2,3])
b = np.array([5,6,7])

c = a + b
print(c)

[ 6  8 10]


In [43]:
# Subtraction: Subtracts two arrays element-wise.
d = b - a
print(d)

[4 4 4]


In [44]:
# Multiplication: Multiplies two arrays element-wise.
e = a * b
print(e)

[ 5 12 21]


In [47]:
# Division: Divides two arrays element-wise.
f = b / a
print(f)

[5.         3.         2.33333333]


In [48]:
# Square Root(np.sqrt()): Computes the square root of each element in the array.
a = np.array([1,2,3])

b = np.sqrt(a)
print(b)

[1.         1.41421356 1.73205081]


In [49]:
# Exponential(np.exp()): Computes the exponential of each element in the array.
a = np.array([1,2])
b = np.exp(a)
print(b)

[2.71828183 7.3890561 ]


**Boardcasting**

- Broadcasting is a powerful mechanism in NumPy that allows arithmetic operations between arrays with different shapes.
- It automatically duplicates the smaller array along the missing dimensions to match the shape of the larger array.
- This makes it possible to perform operations on arrays with different shapes without explicitly reshaping them.

In [51]:
# Different shapes: (2, 3) and (3, 2)
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 2], [3, 4], [5, 6]])
c = a + b  

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [50]:
# 2D array and 1D array
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])
c = a + b
print(c)

[[11 22 33]
 [14 25 36]]
